name: macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build & Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: build-test
        run: make test
