name: Windows

on:
  push:
    branches: [ main ]
    tags: 'v*.*.*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1
      - name: Windows build
        run: msbuild Yuescript.sln -p:Configuration=debug

